### ISSUE TITLE
Why repo instead of branch

### ISSUE THREAD

**Issue by asymmetric** [b4b4r07/zplug2#1]
Hi @b4b4r07 ,

I'm just curious: why did you decide to make a whole new repo, instead of just making a feature branch?

Thanks!

**Comment by babarot** [comment]
Hi!

Thank you for the question. It's because concentrate on the development of version 2.
After the development, [this repo will be merged](https://github.com/b4b4r07/zplug2#migration) into upstream ([zplug](https://github.com/b4b4r07/zplug)).

**Comment by NigoroJr** [comment]
I really don't know if this will be useful or not, but I wrote a script so that I can go back and forth between the two versions easily. I personally found this method to be the less troublesome.

https://gist.github.com/NigoroJr/d2dc0b3a8363e67ebfc0

**Comment by babarot** [comment]
:+1: 

For now, zplug v1 and v2 are compatible. It seems to be able to switch zplug version easily.
