### ISSUE TITLE
Test removes ZPLUG_EXTERNAL

### ISSUE THREAD

**Issue by NigoroJr** [b4b4r07/zplug2#11]
[This line](https://github.com/b4b4r07/zplug2/blob/4942a0aee1968a352b600b54c2f172fcf5c1cd0e/test/autoload/utils/__add___test.zsh#L32) removes the `init.zsh` after running tests. Maybe change the default name for the `ZPLUG_EXTERNAL` file?

**Comment by babarot** [comment]
Oops, my bad. Maybe that should be `$_ZPLUG_CACHE_FILE`

**Comment by NigoroJr** [comment]
I see. Although, I think `$ZPLUG_EXTERNAL` still needs to be changed because it currently points to `$ZPLUG_HOME/init.zsh`.

**Comment by babarot** [comment]
I agree. I'll fix or remove that line.

**Comment by NigoroJr** [comment]
Sounds good :+1:
